GAME_RES=(500, 800)
GAME_FPS=60

BG_IMAGE="assets/vesmír.jpg"
SHIP_IMAGE="assets/ship3.png"
METEOR_IMAGE="assets/Meteorit2.png"

FONT_TYPE="comicsans"
FONT_SIZE=50
FONT_COLOR=(255, 255, 255)

SHIP_SPEED=5
SHIP_BASE_CORD=(250, 720)

METEOR_BASE_COUNT=4
METEOR_COUNT_INCREMENT=4
METEOR_BASE_SPEED=1
METEOR_SPEED_INCREMENT=1
